apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_c9664321c09f5f23b4d37a8ac323fc7b.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_c9664321c09f5f23b4d37a8ac323fc7b.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_c9664321c09f5f23b4d37a8ac323fc7b.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_c9664321c09f5f23b4d37a8ac323fc7b.automount }}
