{{- if .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.workload_kind }}
    name: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.workload_name }}
  minReplicas: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_3cf4a5d4f93c5766aea2a55a19752e42.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}