{{- if .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.workload_kind }}
    name: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.workload_name }}
  minReplicas: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_08a359023748517f9a6fa2cd84e1a845.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}