apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_0e06f687265f5b9faf8c10b4a82aa713.name   }}
spec:
  type: {{ .Values.helm_service_0e06f687265f5b9faf8c10b4a82aa713.type }}
  ports:
    - port: {{ .Values.helm_service_0e06f687265f5b9faf8c10b4a82aa713.port }}
      targetPort: {{ .Values.helm_service_0e06f687265f5b9faf8c10b4a82aa713.target_port }}
      protocol: {{.Values.helm_service_0e06f687265f5b9faf8c10b4a82aa713.protocol}}
  {{- with .Values.helm_service_0e06f687265f5b9faf8c10b4a82aa713.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}