apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_cd3064041cf15bbba31e1dc6e7966ea2.name   }}
spec:
  type: {{ .Values.helm_service_cd3064041cf15bbba31e1dc6e7966ea2.type }}
  ports:
    - port: {{ .Values.helm_service_cd3064041cf15bbba31e1dc6e7966ea2.port }}
      targetPort: {{ .Values.helm_service_cd3064041cf15bbba31e1dc6e7966ea2.target_port }}
      protocol: {{.Values.helm_service_cd3064041cf15bbba31e1dc6e7966ea2.protocol}}
  {{- with .Values.helm_service_cd3064041cf15bbba31e1dc6e7966ea2.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}