apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_814e7456c6bb5068bbb3a7dde5eb7ea4.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_814e7456c6bb5068bbb3a7dde5eb7ea4.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_814e7456c6bb5068bbb3a7dde5eb7ea4.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_814e7456c6bb5068bbb3a7dde5eb7ea4.automount }}
