{{- if .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.workload_kind }}
    name: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.workload_name }}
  minReplicas: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_a996c224f9d757b1b8c6a0b55d394e8a.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}