apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_356efdd651125d6781d636e4414e8c6a.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_356efdd651125d6781d636e4414e8c6a.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_356efdd651125d6781d636e4414e8c6a.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_356efdd651125d6781d636e4414e8c6a.automount }}
